"""Stable reason codes for the decision trace framework."""

from __future__ import annotations

# Trace lifecycle
TRACE_ENABLED = "TRACE_ENABLED"
TRACE_EMPTY = "TRACE_EMPTY"

# Planner / policy (Phase 2)
NO_STEP_REQUIRES_SATISFIED = "NO_STEP_REQUIRES_SATISFIED"
STEP_SELECTED = "STEP_SELECTED"
REQUIREMENT_UNSATISFIED = "REQUIREMENT_UNSATISFIED"
SLOTS_INCOMPLETE = "SLOTS_INCOMPLETE"
CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
CUSTOMER_CONTACT_NAME_REQUIRED = "CUSTOMER_CONTACT_NAME_REQUIRED"
CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
STATUS_READY = "STATUS_READY"
STATUS_AWAITING_CAPABILITY = "STATUS_AWAITING_CAPABILITY"
STAGE_DERIVED_FROM_ACTION = "STAGE_DERIVED_FROM_ACTION"
STAGE_DERIVED_FROM_STATUS = "STAGE_DERIVED_FROM_STATUS"
EXECUTION_ROUTE_BROWSE = "EXECUTION_ROUTE_BROWSE"
EXECUTION_ROUTE_PLAN = "EXECUTION_ROUTE_PLAN"
TIME_SELECTION_READY = "TIME_SELECTION_READY"
BROWSE_OPERATION_DETECTED = "BROWSE_OPERATION_DETECTED"

# Inputs
INPUT_IGNORED_NOT_APPLICABLE = "INPUT_IGNORED_NOT_APPLICABLE"
INPUT_IGNORED_SUPERSEDED = "INPUT_IGNORED_SUPERSEDED"

# Business facts
AVAILABILITY_CHECK_REQUIRED = "AVAILABILITY_CHECK_REQUIRED"
AVAILABILITY_READY = "AVAILABILITY_READY"
FACTS_DERIVED = "FACTS_DERIVED"
AVAILABILITY_NOT_READY = "AVAILABILITY_NOT_READY"
TIME_SELECTION_NOT_READY = "TIME_SELECTION_NOT_READY"

# Fingerprint
BOUND_DATETIME_BYPASS = "BOUND_DATETIME_BYPASS"
CONFIRM_CONTINUATION_BYPASS = "CONFIRM_CONTINUATION_BYPASS"
FINGERPRINT_MISMATCH = "FINGERPRINT_MISMATCH"

# Binding
BIND_NO_EXACT_TIME = "BIND_NO_EXACT_TIME"
BIND_NO_PRESENTED_OFFERS = "BIND_NO_PRESENTED_OFFERS"
BIND_NO_USER_TIME = "BIND_NO_USER_TIME"
BIND_TIME_MISMATCH = "BIND_TIME_MISMATCH"
BIND_DATE_MISMATCH = "BIND_DATE_MISMATCH"
BIND_PARSE_FAILED = "BIND_PARSE_FAILED"
BIND_NORMALIZE_FAILED = "BIND_NORMALIZE_FAILED"
BIND_SKIPPED = "BIND_SKIPPED"

# Merge
MERGE_ELIGIBLE = "MERGE_ELIGIBLE"
MERGE_SKIPPED = "MERGE_SKIPPED"
SLOT_ADDITIVE_MERGE = "SLOT_ADDITIVE_MERGE"
SLOT_PRESERVED_DURABLE = "SLOT_PRESERVED_DURABLE"
ENTITY_RESOLUTION_APPLIED = "ENTITY_RESOLUTION_APPLIED"
ENTITY_RESOLUTION_BLOCKED = "ENTITY_RESOLUTION_BLOCKED"

# Browse / pagination
BROWSE_EXHAUSTED = "BROWSE_EXHAUSTED"
BROWSE_NEXT = "BROWSE_NEXT"
BROWSE_NOT_DETECTED = "BROWSE_NOT_DETECTED"
PAGINATION_HANDLED = "PAGINATION_HANDLED"
PAGINATION_SKIPPED = "PAGINATION_SKIPPED"

# Confirmation gate
CONFIRMATION_ACCEPT = "CONFIRMATION_ACCEPT"
CONFIRMATION_ENTER_PENDING = "CONFIRMATION_ENTER_PENDING"
CONFIRMATION_GATE_CLOSED = "CONFIRMATION_GATE_CLOSED"
CONFIRMATION_GATE_OPEN = "CONFIRMATION_GATE_OPEN"
CONFIRMATION_REJECT = "CONFIRMATION_REJECT"
CONFIRMATION_ANOTHER_REQUEST = "CONFIRMATION_ANOTHER_REQUEST"

# Binding / pagination / fingerprint (reserved)
BIND_EXACT_TIME_MATCH = "BIND_EXACT_TIME_MATCH"
TIME_MATCH_EXACT = "TIME_MATCH_EXACT"
TIME_MATCH_MISMATCH = "TIME_MATCH_MISMATCH"
BROWSE_PREVIOUS = "BROWSE_PREVIOUS"
FINGERPRINT_MATCH = "FINGERPRINT_MATCH"

# Phase 1 spine — execution eligibility
PLAN_ACTION_PRESENT = "PLAN_ACTION_PRESENT"
PLAN_ACTION_MISSING = "PLAN_ACTION_MISSING"
PAGINATION_SHORT_CIRCUIT = "PAGINATION_SHORT_CIRCUIT"
NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
HANDLER_DELEGATED = "HANDLER_DELEGATED"
PLANNING_FAILED = "PLANNING_FAILED"

# Phase 1 spine — persistence
PERSIST_SAVE_APPLIED = "PERSIST_SAVE_APPLIED"
PERSIST_SAVE_SKIPPED_STATUS = "PERSIST_SAVE_SKIPPED_STATUS"
PERSIST_SAVE_SKIPPED_NO_STATE = "PERSIST_SAVE_SKIPPED_NO_STATE"
RELOAD_MATCH = "RELOAD_MATCH"
RELOAD_MISMATCH = "RELOAD_MISMATCH"
RELOAD_SKIPPED = "RELOAD_SKIPPED"

# Phase 1 spine — turn outcome
TURN_OUTCOME_EXECUTED = "TURN_OUTCOME_EXECUTED"
TURN_OUTCOME_HANDLER_DELEGATED = "TURN_OUTCOME_HANDLER_DELEGATED"
TURN_OUTCOME_ERROR = "TURN_OUTCOME_ERROR"

# Phase 1 architecture — observational ownership model (not consumed by Decision)
ARCH_CURRENT_REQUEST = "ARCH_CURRENT_REQUEST"
ARCH_ATTACHED_REQUEST = "ARCH_ATTACHED_REQUEST"
ARCH_LEGACY_ATTACHMENT_READS = "ARCH_LEGACY_ATTACHMENT_READS"
ARCH_CONVERSATION_CONTEXT = "ARCH_CONVERSATION_CONTEXT"
ARCH_RELATIONSHIP_EVALUATION = "ARCH_RELATIONSHIP_EVALUATION"
ARCH_FINAL_DECISION = "ARCH_FINAL_DECISION"
ARCH_DECISION_INPUT = "ARCH_DECISION_INPUT"
ARCH_EXTERNAL_DECISION_WRITERS = "ARCH_EXTERNAL_DECISION_WRITERS"
