AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dialogcart Intent Service (Embeddings + Nearest Centroid)

Parameters:
  # Set to 0 (or remove entirely) to avoid PC failures/prompts
  ProvisionedConcurrency:
    Type: Number
    Default: 0
  MemorySize:
    Type: Number
    Default: 3008
  Timeout:
    Type: Number
    Default: 60
  SimThreshold:
    Type: String
    Default: "0.60"
  MarginThreshold:
    Type: String
    Default: "0.08"
  EmbedPrefix:
    Type: String
    Default: "ecommerce intent: "

Resources:
  IntentBucket:
    Type: AWS::S3::Bucket

  IntentApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: v1
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','OPTIONS']
        AllowHeaders: ['*']

  IntentFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: !Ref Timeout
      MemorySize: !Ref MemorySize
      Architectures: [ x86_64 ]
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref IntentBucket
        - S3WritePolicy:
            BucketName: !Ref IntentBucket
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          S3_BUCKET: !Ref IntentBucket
          S3_KEY: intents/prod/intents.json
          SIM_THRESHOLD: !Ref SimThreshold
          MARGIN_THRESHOLD: !Ref MarginThreshold
          EMBED_PREFIX: !Ref EmbedPrefix
      Events:
        Predict:
          Type: HttpApi
          Properties:
            Path: /predict
            Method: POST
            ApiId: !Ref IntentApi
        Train:
          Type: HttpApi
          Properties:
            Path: /train
            Method: POST
            ApiId: !Ref IntentApi
        Warm:
          Type: HttpApi
          Properties:
            Path: /warm
            Method: GET
            ApiId: !Ref IntentApi
      AutoPublishAlias: live
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs:
        BUILD_ID: "19"   # bump to force new image digest

  # Scheduled warm (invokes Lambda directly; no API GW 30s cap)
  
  WarmRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt IntentFunction.Arn
          Id: WarmTarget
          Input: '{"source": "dialogcart.warm"}'

  WarmInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: WarmRule  # <--- fixes circular dependency
    Properties:
      FunctionName: !Ref IntentFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com



Outputs:
  ApiBaseUrl:
    Description: Invoke base URL
    Value: !Sub "https://${IntentApi}.execute-api.${AWS::Region}.amazonaws.com/v1/"
  BucketName:
    Description: Centroid bucket
    Value: !Ref IntentBucket
  FunctionAliasArn:
    Description: Lambda alias ARN (live)
    Value: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${IntentFunction}:live"
