"""
ClarificationReason Enum

Finite enum of all clarification reasons.
Enum values are stable, snake_case strings.
"""

from enum import Enum


class ClarificationReason(Enum):
    """Enumeration of all clarification reasons."""

    AMBIGUOUS_TIME_NO_WINDOW = "AMBIGUOUS_TIME_NO_WINDOW"
    AMBIGUOUS_DATE_MULTIPLE = "AMBIGUOUS_DATE_MULTIPLE"
    MISSING_TIME = "MISSING_TIME"
    MISSING_DATE = "MISSING_DATE"
    MISSING_SERVICE = "MISSING_SERVICE"
    LOCALE_AMBIGUOUS_DATE = "LOCALE_AMBIGUOUS_DATE"
    VAGUE_DATE_REFERENCE = "VAGUE_DATE_REFERENCE"
    AMBIGUOUS_PLURAL_WEEKDAY = "AMBIGUOUS_PLURAL_WEEKDAY"
    AMBIGUOUS_WEEKDAY_REFERENCE = "AMBIGUOUS_WEEKDAY_REFERENCE"
    CONFLICTING_SIGNALS = "CONFLICTING_SIGNALS"
    CONTEXT_DEPENDENT_DATE = "CONTEXT_DEPENDENT_DATE"
    CONTEXT_DEPENDENT_VALUE = "CONTEXT_DEPENDENT_VALUE"
    MISSING_BOOKING_REFERENCE = "MISSING_BOOKING_REFERENCE"
    MISSING_DATE_FOR_TIME_CONSTRAINT = "MISSING_DATE_FOR_TIME_CONSTRAINT"
    MISSING_CONTEXT = "MISSING_CONTEXT"
    SERVICE_VARIANT = "SERVICE_VARIANT"
