"""
ClarificationReason Enum

Finite enum of all clarification reasons.
Enum values are stable, snake_case strings.
"""

from enum import Enum


class ClarificationReason(Enum):
    """Enumeration of all clarification reasons."""

    AMBIGUOUS_TIME_NO_WINDOW = "AMBIGUOUS_TIME_NO_WINDOW"
    AMBIGUOUS_DATE_MULTIPLE = "AMBIGUOUS_DATE_MULTIPLE"
    AMBIGUOUS_TIME_MERIDIEM = "AMBIGUOUS_TIME_MERIDIEM"
    MISSING_TIME = "MISSING_TIME"
    MISSING_DATE = "MISSING_DATE"
    MISSING_SERVICE = "MISSING_SERVICE"
    LOCALE_AMBIGUOUS_DATE = "LOCALE_AMBIGUOUS_DATE"
    VAGUE_DATE_REFERENCE = "VAGUE_DATE_REFERENCE"
    AMBIGUOUS_PLURAL_WEEKDAY = "AMBIGUOUS_PLURAL_WEEKDAY"
    AMBIGUOUS_WEEKDAY_REFERENCE = "AMBIGUOUS_WEEKDAY_REFERENCE"
    CONFLICTING_SIGNALS = "CONFLICTING_SIGNALS"
    CONTEXT_DEPENDENT_DATE = "CONTEXT_DEPENDENT_DATE"
    CONTEXT_DEPENDENT_VALUE = "CONTEXT_DEPENDENT_VALUE"
    MISSING_BOOKING_REFERENCE = "MISSING_BOOKING_REFERENCE"
    MISSING_DATE_FOR_TIME_CONSTRAINT = "MISSING_DATE_FOR_TIME_CONSTRAINT"
    MISSING_CONTEXT = "MISSING_CONTEXT"
    MULTIPLE_MATCHES = "MULTIPLE_MATCHES"
    INCOMPLETE_BINDING = "INCOMPLETE_BINDING"
    UNSUPPORTED_SERVICE = "UNSUPPORTED_SERVICE"
    # AMBIGUOUS_SERVICE removed - replaced with MULTIPLE_MATCHES for consistency
    MISSING_TIME_FUZZY = "MISSING_TIME_FUZZY"
    POLICY_TIME_WINDOW = "POLICY_TIME_WINDOW"
    POLICY_CONSTRAINT_ONLY_TIME = "POLICY_CONSTRAINT_ONLY_TIME"
