[pytest]
pythonpath = .
testpaths = luma/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# Use shorter traceback format to reduce code dumps
addopts = --tb=short

